name: libreforge
version: ${projectVersion}
main: com.willfp.libreforge.LibreforgeSpigotPlugin
api-version: 1.17
authors: [ Auxilor ]
website: willfp.com

# eco is written as a softdepend because otherwise the plugin
# loader will complain about it not being installed.

# I also can't use paper-plugin.yml because that doesn't support
# being loaded at runtime.

softdepend:
  - eco
  - AureliumSkills
  - Jobs
  - LevelledMobs
  - mcMMO
  - Scyther
  - TMMobcoins
  - Vault

commands:
  lrcdb:
    description: Handles lrcdb
    permission: libreforge.command.lrcdb
  libreforge:
    description: Base libreforge command
    permission: libreforge.command.libreforge

permissions:
  libreforge.*:
    description: All libreforge permissions
    default: op
    children:
      libreforge.command.*: true
  libreforge.command.*:
    description: All commands
    default: op
    children:
      libreforge.command.lrcdb: true
      libreforge.command.libreforge: true
      libreforge.command.reload: true
  libreforge.command.lrcdb:
    description: Allows the use of /lrcdb
    default: op
  libreforge.command.libreforge:
    description: Allows the use of /libreforge
    default: op
  libreforge.command.reload:
    description: Allows the use of /libreforge reload
    default: op
